// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback to known values if environment variables are not loaded
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://kdqibmhpebndlmzjhuvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcWlibWhwZWJuZGxtempodXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMDg2ODIsImV4cCI6MjA3NDg4NDY4Mn0.vNZuF9QMc5T4me8V71zCOTJgyBgN0DZxPO_gRCAAmA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});